# @package _global_

trainer:
  _target_: lightning.pytorch.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 100
  accelerator: gpu
  devices: auto
  strategy: fsdp
  precision: 32
  accumulate_grad_batches: 1
  deterministic: False
