# @package _global_

model:
  _target_: simplefold.model.simplefold.SimpleFold
  architecture: ${model.architecture}
  processor: ${model.processor}
  loss: ${model.loss}
  path: ${model.path}
  sampler: ${model.sampler}
  use_bayesian_loss: False
  bayesian_loss_type: "noe_geom"
  bayesian_beta_start: 0.0
  bayesian_beta_end: 0.0
  noe_potential_type: "gaussian"
  noe_base_sigma: 0.5
  noe_time_dependent: True
  geometric_clash_cutoff: 2.5
  geometric_clash_penalty: 10.0
  geometric_covalent_penalty: 5.0
  smooth_lddt_loss_weight: 1.0
  lddt_cutoff: 15.0
  clip_grad_norm_val: 1.0
  lddt_weight_schedule: False
  plddt_training: False
